/**
 * Frontend Real-Time Event Types Standard
 * Matches backend event definitions for unified synchronization.
 */

export const EVENT_TYPES = {
  // Generic Entity Actions
  ENTITY_CREATED: 'ENTITY_CREATED',
  ENTITY_UPDATED: 'ENTITY_UPDATED',
  ENTITY_DELETED: 'ENTITY_DELETED',

  // Order & Transaction Domain
  ORDER_CREATED: 'ORDER_CREATED',
  ORDER_UPDATED: 'ORDER_UPDATED',
  ORDER_STATUS_CHANGED: 'ORDER_STATUS_CHANGED',
  ORDER_CANCELLED: 'ORDER_CANCELLED',

  // Catalog & Product Domain
  PRODUCT_CREATED: 'PRODUCT_CREATED',
  PRODUCT_UPDATED: 'PRODUCT_UPDATED',
  PRODUCT_DELETED: 'PRODUCT_DELETED',
  STOCK_UPDATED: 'STOCK_UPDATED',

  // Delivery Partner Domain
  PARTNER_CREATED: 'PARTNER_CREATED',
  PARTNER_UPDATED: 'PARTNER_UPDATED',
  PARTNER_DELETED: 'PARTNER_DELETED',
  PARTNER_STATUS_CHANGED: 'PARTNER_STATUS_CHANGED',

  // Customer & Patient Domain
  CUSTOMER_CREATED: 'CUSTOMER_CREATED',
  CUSTOMER_UPDATED: 'CUSTOMER_UPDATED',
  PATIENT_UPDATED: 'PATIENT_UPDATED',
  APPOINTMENT_CREATED: 'APPOINTMENT_CREATED',
  APPOINTMENT_UPDATED: 'APPOINTMENT_UPDATED',

  // Vendor & Outlets Domain
  VENDOR_UPDATED: 'VENDOR_UPDATED',
  VENDOR_STATUS_CHANGED: 'VENDOR_STATUS_CHANGED',
  BUSINESS_OUTLET_CREATED: 'BUSINESS_OUTLET_CREATED',
  BUSINESS_OUTLET_UPDATED: 'BUSINESS_OUTLET_UPDATED',
  PROFILE_UPDATED: 'PROFILE_UPDATED',

  // System & Connection Heartbeat
  SYSTEM_PING: 'SYSTEM_PING',
  SYSTEM_PONG: 'SYSTEM_PONG',
  SYNC_REQUEST: 'SYNC_REQUEST',
  SYNC_RESPONSE: 'SYNC_RESPONSE'
};
